"""Core primitives for the Cognitive Execution Engine."""

from .approval import (
    ApprovalAuditEvent,
    ApprovalDecision,
    ApprovalGate,
    ApprovalGateResult,
    ApprovalProvider,
    CallbackApprovalProvider,
    StaticApprovalProvider,
    approve_transition,
)
from .anthropic_compatible_provider import (
    ANTHROPIC_COMPAT_BASE_URL_ENV,
    ANTHROPIC_COMPAT_DEFAULT_MODEL,
    ANTHROPIC_COMPAT_ENV_KEY,
    ANTHROPIC_COMPAT_MODEL_ENV,
    anthropic_compatible_messages_transport,
    build_anthropic_compatible_request_body,
    build_anthropic_compatible_task_compiler_provider,
    extract_anthropic_compatible_text,
)
from .artifacts import (
    dumps_event_payloads,
    events_to_payloads,
    loads_event_payloads,
    replay_event_payload_artifact,
)
from .calibration import (
    CalibrationResult,
    calibration_proposal_to_patch,
    run_calibration_cycle,
)
from .change_test import (
    ChangeProposal,
    ChangeTestResult,
    evaluate_change_test,
)
from .audit_policy import CompilerAuditPolicy
from .confidence_gate import ConfidenceGateConfig, evaluate_confidence_gate, extract_belief_confidence
from .belief_update import build_belief_payload, promote_observation_to_belief_patch
from .deliberation import NextAction, ReasoningChain, ReasoningStep, deliberate_chain, deliberate_next_action
from .domain_context import DomainContext, build_domain_context
from .domain_policy import evaluate_patch_policy_in_domain
from .domain_plugins import (
    ConnectorSpec,
    DomainPluginPack,
    DomainPluginRegistry,
    DomainRulePack,
    EvaluatorPlugin,
    GlossaryPack,
)
from .event_log import (
    EventLog,
    replay_serialized_transition_events,
    replay_transition_events,
)
from .events import DeliberationEvent, Event, StateTransitionEvent
from .failure_modes import (
    FailureMode,
    FailureRecord,
    classify_exception,
    describe_failure_mode,
    record_failure,
)
from .handoff_report import build_handoff_report, render_handoff_report
from .handoff_stage_checker import HandoffStageResult, assess_handoff_stage_gates
from .handoff_validator import (
    HandoffValidationResult,
    load_handoff_state,
    validate_handoff_state,
    validate_handoff_state_file,
)
from .llm_task_adapter import (
    LLMTaskCompiler,
    ProviderBackedTaskCompiler,
    StaticLLMTaskCompiler,
    build_task_compiler_prompt,
    compile_task_with_llm_adapter,
    parse_llm_task_response,
)
from .llm_provider import (
    FailingLLMProvider,
    LLMProvider,
    LLMProviderError,
    LLMProviderRequest,
    LLMProviderResponse,
    StaticLLMProvider,
    EmbeddingProvider,
    StaticEmbeddingProvider,
    get_default_embedding_provider,
)
from .narration import render_event_narration
from .optional_provider import (
    EnvironmentLLMProvider,
    ProviderTransport,
    build_disabled_provider_transport,
)
from .quality_report import build_quality_report, render_quality_report
from .quality_thresholds import (
    QualityGateCheck,
    QualityGateResult,
    assess_quality_gates,
    assess_quality_gates_for_run,
)
from .quality_metrics import QualityMetrics, compute_quality_metrics
from .primitives import (
    ALL_COGNITIVE_PRIMITIVES,
    CognitivePrimitive,
    default_primitives_for_task_kind,
    validate_primitives,
)
from .observations import (
    BeliefCandidate,
    ObservationCandidate,
    ObservationEvent,
    ReflectionCandidate,
    build_observation_event,
    observation_from_tool_result,
    promote_belief_candidate_to_patch,
    promote_observation_to_patch,
)
from .openai_provider import (
    OPENAI_DEFAULT_MODEL,
    OPENAI_ENV_KEY,
    OPENAI_MODEL_ENV,
    TASK_SPEC_JSON_SCHEMA,
    build_openai_task_compiler_provider,
    openai_responses_task_compiler_transport,
    openai_responses_task_compiler_transport_with_client,
)
from .planner import PlanExecutionResult, PlanSpec, execute_plan, plan_from_task
from .policy import PolicyDecision, build_transition_for_patch, evaluate_patch_policy
from .runtime import (
    RunResult,
    execute_task,
    execute_task_in_domain,
    execute_task_with_chain,
    execute_task_with_compiler,
    execute_task_with_compiler_in_domain,
)
from .run_artifact import (
    RUN_ARTIFACT_SCHEMA_VERSION,
    RunArtifact,
    replay_run_artifact_json,
    run_result_to_artifact,
)
from .schemas import (
    DELIBERATION_EVENT_SCHEMA_VERSION,
    PATCH_SCHEMA_VERSION,
    PLAN_SCHEMA_VERSION,
    POLICY_DECISION_SCHEMA_VERSION,
    REASONING_STEP_SCHEMA_VERSION,
    SCHEMA_MAJOR_VERSION,
    STATE_TRANSITION_EVENT_SCHEMA_VERSION,
    TASK_SCHEMA_VERSION,
    require_schema_version,
)
from .self_observation import (
    BehavioralSnapshot,
    CalibrationProposal,
    RedirectProposal,
    extract_behavioral_snapshot,
    propose_self_model_calibration,
    reflect_and_redirect,
)
from .state import State, StatePatch, apply_patch, reduce_event, replay
from .tasks import TaskLevel, TaskSpec, classify_task_level, compile_task
from .tool_runner import InMemoryReadOnlyToolRunner, ReadToolHandler
from .tool_observation_flow import (
    ToolObservationFlowResult,
    PlannerToolExecutionResult,
    execute_plan_with_read_only_tools,
    run_allowed_tool_call_observation_flow,
    run_read_only_tool_observation_flow,
)
from .tools import (
    ToolCallEvent,
    ToolCallSpec,
    ToolPolicyDecision,
    ToolRegistry,
    ToolResultEvent,
    ToolSpec,
    build_tool_call_event,
    evaluate_tool_call_policy,
)
from .memory_types import PrecedentMemory, MemoryRetrievalResult
from .retrieval_types import (
    EvidenceNode,
    EvidenceEdge,
    EvidenceGraph,
    EvidenceNodeType,
    EvidenceEdgeType,
    RetrievalQuery,
)
from .memory_store import MemoryStore
from .memory_index import MemoryIndex
from .contextualizer import Contextualizer, DocumentChunk
from .retriever import Retriever, RetrievalResult
from .evidence_graph import EvidenceGraphBuilder, EvidenceGraphAnalyzer
from .context_restorer import ContextRestorer, RestoredContext, ExecutionStage
from .uncertainty_router import (
    UncertaintyRouter,
    RoutingSignals,
    RoutingResult,
    RoutingDecision,
    RouterConfig,
)
from .approval_packet import ApprovalPacket, ApprovalVerdict
from .ab_testing import (
    ABTestingFramework,
    ABExperiment,
    ExperimentVariant,
    ExperimentResult,
    ExperimentAnalysis,
    ExperimentStatus,
)

__all__ = [
    "ApprovalAuditEvent",
    "ApprovalDecision",
    "ApprovalGate",
    "ApprovalGateResult",
    "ApprovalProvider",
    "CallbackApprovalProvider",
    "StaticApprovalProvider",
    "ANTHROPIC_COMPAT_BASE_URL_ENV",
    "ANTHROPIC_COMPAT_DEFAULT_MODEL",
    "ANTHROPIC_COMPAT_ENV_KEY",
    "ANTHROPIC_COMPAT_MODEL_ENV",
    "approve_transition",
    "anthropic_compatible_messages_transport",
    "CalibrationResult",
    "ChangeProposal",
    "ChangeTestResult",
    "CompilerAuditPolicy",
    "ConfidenceGateConfig",
    "evaluate_change_test",
    "evaluate_confidence_gate",
    "extract_belief_confidence",
    "DomainContext",
    "ConnectorSpec",
    "DomainPluginPack",
    "DomainPluginRegistry",
    "DomainRulePack",
    "deliberate_next_action",
    "deliberate_chain",
    "DeliberationEvent",
    "dumps_event_payloads",
    "EventLog",
    "Event",
    "FailureMode",
    "FailureRecord",
    "HandoffStageResult",
    "events_to_payloads",
    "HandoffValidationResult",
    "LLMTaskCompiler",
    "LLMProvider",
    "LLMProviderError",
    "LLMProviderRequest",
    "LLMProviderResponse",
    "ProviderBackedTaskCompiler",
    "ProviderTransport",
    "FailingLLMProvider",
    "EnvironmentLLMProvider",
    "EvaluatorPlugin",
    "ALL_COGNITIVE_PRIMITIVES",
    "CognitivePrimitive",
    "OPENAI_DEFAULT_MODEL",
    "OPENAI_ENV_KEY",
    "OPENAI_MODEL_ENV",
    "NextAction",
    "ObservationCandidate",
    "ObservationEvent",
    "GlossaryPack",
    "StaticLLMTaskCompiler",
    "StaticLLMProvider",
    "EmbeddingProvider",
    "StaticEmbeddingProvider",
    "get_default_embedding_provider",
    "TASK_SPEC_JSON_SCHEMA",
    "build_disabled_provider_transport",
    "build_anthropic_compatible_request_body",
    "build_belief_payload",
    "build_domain_context",
    "build_handoff_report",
    "assess_handoff_stage_gates",
    "evaluate_patch_policy_in_domain",
    "build_anthropic_compatible_task_compiler_provider",
    "build_openai_task_compiler_provider",
    "build_observation_event",
    "build_quality_report",
    "StateTransitionEvent",
    "PlanExecutionResult",
    "PlanSpec",
    "PlannerToolExecutionResult",
    "PolicyDecision",
    "QualityGateCheck",
    "QualityGateResult",
    "QualityMetrics",
    "ReasoningStep",
    "ReasoningChain",
    "RunResult",
    "RunArtifact",
    "DELIBERATION_EVENT_SCHEMA_VERSION",
    "PATCH_SCHEMA_VERSION",
    "PLAN_SCHEMA_VERSION",
    "POLICY_DECISION_SCHEMA_VERSION",
    "REASONING_STEP_SCHEMA_VERSION",
    "RUN_ARTIFACT_SCHEMA_VERSION",
    "SCHEMA_MAJOR_VERSION",
    "STATE_TRANSITION_EVENT_SCHEMA_VERSION",
    "TASK_SCHEMA_VERSION",
    "TaskLevel",
    "TaskSpec",
    "InMemoryReadOnlyToolRunner",
    "ReadToolHandler",
    "ToolCallSpec",
    "ToolCallEvent",
    "ToolPolicyDecision",
    "ToolRegistry",
    "ToolResultEvent",
    "ToolObservationFlowResult",
    "ToolSpec",
    "build_transition_for_patch",
    "build_task_compiler_prompt",
    "build_tool_call_event",
    "compile_task",
    "classify_exception",
    "classify_task_level",
    "compile_task_with_llm_adapter",
    "describe_failure_mode",
    "default_primitives_for_task_kind",
    "evaluate_patch_policy",
    "evaluate_tool_call_policy",
    "execute_task",
    "execute_task_in_domain",
    "execute_task_with_chain",
    "execute_task_with_compiler",
    "execute_task_with_compiler_in_domain",
    "execute_plan",
    "execute_plan_with_read_only_tools",
    "extract_anthropic_compatible_text",
    "loads_event_payloads",
    "load_handoff_state",
    "assess_quality_gates",
    "assess_quality_gates_for_run",
    "compute_quality_metrics",
    "render_event_narration",
    "render_handoff_report",
    "render_quality_report",
    "plan_from_task",
    "parse_llm_task_response",
    "openai_responses_task_compiler_transport",
    "openai_responses_task_compiler_transport_with_client",
    "observation_from_tool_result",
    "promote_observation_to_belief_patch",
    "promote_observation_to_patch",
    "reflect_and_redirect",
    "RedirectProposal",
    "record_failure",
    "State",
    "StatePatch",
    "apply_patch",
    "reduce_event",
    "replay",
    "replay_event_payload_artifact",
    "replay_run_artifact_json",
    "replay_serialized_transition_events",
    "replay_transition_events",
    "require_schema_version",
    "run_result_to_artifact",
    "run_allowed_tool_call_observation_flow",
    "run_read_only_tool_observation_flow",
    "validate_handoff_state",
    "validate_handoff_state_file",
    "validate_primitives",
    # Plan B new modules
    "PrecedentMemory",
    "MemoryRetrievalResult",
    "EvidenceNode",
    "EvidenceEdge",
    "EvidenceGraph",
    "EvidenceNodeType",
    "EvidenceEdgeType",
    "RetrievalQuery",
    "MemoryStore",
    "MemoryIndex",
    "Contextualizer",
    "DocumentChunk",
    "Retriever",
    "RetrievalResult",
    "EvidenceGraphBuilder",
    "EvidenceGraphAnalyzer",
    "ContextRestorer",
    "RestoredContext",
    "ExecutionStage",
    "UncertaintyRouter",
    "RoutingSignals",
    "RoutingResult",
    "RoutingDecision",
    "RouterConfig",
    "ApprovalPacket",
    "ApprovalVerdict",
    "ABTestingFramework",
    "ABExperiment",
    "ExperimentVariant",
    "ExperimentResult",
    "ExperimentAnalysis",
    "ExperimentStatus",
]
