"""Core primitives for the Cognitive Execution Engine."""

from .approval import (
    ApprovalAuditEvent,
    ApprovalDecision,
    ApprovalGate,
    ApprovalGateResult,
    ApprovalProvider,
    CallbackApprovalProvider,
    StaticApprovalProvider,
)
from .anthropic_compatible_provider import (
    ANTHROPIC_COMPAT_BASE_URL_ENV,
    ANTHROPIC_COMPAT_DEFAULT_MODEL,
    ANTHROPIC_COMPAT_ENV_KEY,
    ANTHROPIC_COMPAT_MODEL_ENV,
    anthropic_compatible_messages_transport,
    build_anthropic_compatible_request_body,
    build_anthropic_compatible_task_compiler_provider,
    extract_anthropic_compatible_text,
)
from .artifacts import (
    dumps_event_payloads,
    events_to_payloads,
    loads_event_payloads,
)
from .calibration import (
    CalibrationResult,
    calibration_proposal_to_delta,
    run_calibration_cycle,
)
from .change_test import (
    ChangeProposal,
    ChangeTestResult,
    evaluate_change_test,
)
from .audit_policy import CompilerAuditPolicy
from .belief_update import build_belief_payload, promote_observation_to_belief_delta
from .deliberation import NextAction, ReasoningChain, ReasoningStep, deliberate_chain, deliberate_next_action
from .domain_context import DomainContext, build_domain_context
from .domain_plugins import (
    ConnectorSpec,
    DomainPluginPack,
    DomainPluginRegistry,
    DomainRulePack,
    EvaluatorPlugin,
    GlossaryPack,
)
from .event_log import (
    EventLog,
)
from .events import CommitmentKind, DeliberationEvent, Event
from .failure_modes import (
    FailureMode,
    FailureRecord,
    classify_exception,
    describe_failure_mode,
    record_failure,
)
from .handoff_report import build_handoff_report, render_handoff_report
from .handoff_stage_checker import HandoffStageResult, assess_handoff_stage_gates
from .handoff_validator import (
    HandoffValidationResult,
    load_handoff_state,
    validate_handoff_state,
    validate_handoff_state_file,
)
from .llm_task_adapter import (
    LLMTaskCompiler,
    ProviderBackedTaskCompiler,
    StaticLLMTaskCompiler,
    build_task_compiler_prompt,
    compile_task_with_llm_adapter,
    parse_llm_task_response,
)
from .llm_provider import (
    FailingLLMProvider,
    LLMProvider,
    LLMProviderError,
    LLMProviderRequest,
    LLMProviderResponse,
    StaticLLMProvider,
    EmbeddingProvider,
    StaticEmbeddingProvider,
    get_default_embedding_provider,
)
from .narration import render_event_narration
from .optional_provider import (
    EnvironmentLLMProvider,
    ProviderTransport,
    build_disabled_provider_transport,
)
from .quality_report import build_quality_report, render_quality_report
from .quality_thresholds import (
    QualityGateCheck,
    QualityGateResult,
    assess_quality_gates,
    assess_quality_gates_for_run,
)
from .quality_metrics import QualityMetrics, compute_quality_metrics
from .primitives import (
    ALL_COGNITIVE_PRIMITIVES,
    CognitivePrimitive,
    default_primitives_for_task_kind,
    validate_primitives,
)
from .observations import (
    BeliefCandidate,
    ObservationCandidate,
    ObservationEvent,
    ReflectionCandidate,
    build_observation_event,
    observation_from_tool_result,
    promote_belief_candidate_to_delta,
    promote_observation_to_delta,
)
from .openai_provider import (
    OPENAI_DEFAULT_MODEL,
    OPENAI_ENV_KEY,
    OPENAI_MODEL_ENV,
    TASK_SPEC_JSON_SCHEMA,
    build_openai_task_compiler_provider,
    openai_responses_task_compiler_transport,
    openai_responses_task_compiler_transport_with_client,
)
from .planner import (
    DeltaPolicyDecision,
    PlanExecutionResult,
    PlanSpec,
    evaluate_delta_policy,
    evaluate_delta_policy_in_domain,
    execute_plan,
    plan_from_task,
)
from .runtime import (
    RunResult,
    execute_task,
    execute_task_in_domain,
    execute_task_with_chain,
    execute_task_with_compiler,
    execute_task_with_compiler_in_domain,
)
from .run_artifact import (
    RUN_ARTIFACT_SCHEMA_VERSION,
    RunArtifact,
    run_result_to_artifact,
)
from .schemas import (
    COMMITMENT_POLICY_SCHEMA_VERSION,
    DELIBERATION_EVENT_SCHEMA_VERSION,
    PLAN_SCHEMA_VERSION,
    REASONING_STEP_SCHEMA_VERSION,
    SCHEMA_MAJOR_VERSION,
    TASK_SCHEMA_VERSION,
    require_schema_version,
)
from .self_observation import (
    BehavioralSnapshot,
    CalibrationProposal,
    RedirectProposal,
    extract_behavioral_snapshot,
    propose_self_model_calibration,
    reflect_and_redirect,
)
from .tasks import TaskLevel, TaskSpec, classify_task_level, compile_task
from .tool_runner import InMemoryReadOnlyToolRunner, ReadToolHandler
from .tool_gateway import ToolGateway, ToolGatewayResult, ToolHandler as GatewayToolHandler, ApprovalProvider, StaticApprovalProvider as GatewayStaticApprovalProvider, build_tool_gateway
from .tool_observation_flow import (
    ToolObservationFlowResult,
    PlannerToolExecutionResult,
    execute_plan_with_read_only_tools,
    run_allowed_tool_call_observation_flow,
    run_read_only_tool_observation_flow,
)
from .tools import (
    ToolCallEvent,
    ToolCallSpec,
    ToolPolicyDecision,
    ToolRegistry,
    ToolResultEvent,
    ToolSpec,
    build_tool_call_event,
    evaluate_tool_call_policy,
)
from .memory_types import PrecedentMemory, MemoryRetrievalResult
from .retrieval_types import (
    EvidenceNode,
    EvidenceEdge,
    EvidenceGraph,
    EvidenceNodeType,
    EvidenceEdgeType,
    RetrievalQuery,
)
from .memory_store import MemoryStore
from .memory_index import MemoryIndex
from .contextualizer import Contextualizer, DocumentChunk
from .retriever import Retriever, RetrievalResult
from .evidence_graph import EvidenceGraphBuilder, EvidenceGraphAnalyzer
from .context_restorer import ContextRestorer, RestoredContext, ExecutionStage
from .uncertainty_router import (
    UncertaintyRouter,
    RoutingSignals,
    RoutingResult,
    RoutingDecision,
    RouterConfig,
)
from .approval_packet import ApprovalPacket, ApprovalVerdict
from .ab_testing import (
    ABTestingFramework,
    ABExperiment,
    ExperimentVariant,
    ExperimentResult,
    ExperimentAnalysis,
    ExperimentStatus,
)
from .llm_deliberation import (
    LLMDeliberationCompiler,
    ProviderBackedDeliberationCompiler,
    StaticLLMDeliberationCompiler,
    deliberate_chain_with_llm,
    deliberate_with_llm,
    parse_llm_deliberation_response,
)
from .llm_plan_adapter import (
    LLMPlanCompiler,
    ProviderBackedPlanCompiler,
    StaticLLMPlanCompiler,
    plan_with_llm,
    parse_llm_plan_response,
)
from .embedding_provider import (
    EnvironmentEmbeddingProvider,
    OpenAIEmbeddingProvider,
    build_openai_embedding_provider,
)
from .tool_executor import (
    DefaultToolSandbox,
    SandboxedToolExecutor,
    ToolExecutionContext,
    ToolExecutionResult,
    ToolHandler,
    ToolSandbox,
)
from .persistence import (
    StateStore,
    PersistenceSnapshot,
    EventStoreEntry,
    load_world_state_from_file,
    save_world_state,
    load_world_state,
)
from .observability import (
    ExecutionMetricsCollector,
    ExecutionObserver,
    ExecutionPhase,
    ConsoleMetricsExporter,
    DebugContext,
    ExecutionMetric,
    MetricsExporter,
    PhaseTiming,
)
from .external_gateway import (
    HTTPGateway,
    HTTPGatewayConfig,
    WebhookConfig,
    WebhookDispatcher,
    DefaultWebhookSender,
    RateLimiter,
)
from .import_export import (
    ImportExportManager,
    ExportPackage,
    ExportManifest,
)
from .world_schema import (
    Confidence,
    RevisionDelta,
    RevisionTargetKind,
    WorldEntity,
    WorldHypothesis,
    WorldRelation,
    WORLD_SCHEMA_VERSION,
)
from .world_state import (
    WorldState,
    add_anchor_facts,
    add_entity,
    add_hypothesis_to_world,
    add_relation,
    add_tension,
    remove_entity,
    resolve_tension,
    update_entity,
    update_hypothesis_status,
    update_self_model,
    WORLD_STATE_SCHEMA_VERSION,
)
from .commitment import (
    CommitmentEvent,
    CommitmentKind as FullCommitmentKind,
    Reversibility,
    complete_commitment,
    make_act_commitment,
    make_observation_commitment,
    make_tool_contact_commitment,
    COMMITMENT_SCHEMA_VERSION,
)
from .commitment_policy import (
    CommitmentPolicy,
    CommitmentPolicyDecision,
    DefaultCommitmentPolicy,
    evaluate_commitment_policy,
)
from .revision import (
    ModelRevisionEvent,
    RevisionKind,
    revise_from_commitment,
    REVISION_SCHEMA_VERSION,
)
from .hypothesis_engine import (
    HypothesisCandidate,
    generate_from_tension,
    generate_from_conflict,
    rank_hypotheses,
)
from .revision_policy import (
    DefaultRevisionPolicy,
    RevisionPolicy,
    RevisionPolicyDecision,
    evaluate_revision_policy,
    REVISION_POLICY_SCHEMA_VERSION,
)

__all__ = [
    "ApprovalAuditEvent",
    "ApprovalDecision",
    "ApprovalGate",
    "ApprovalGateResult",
    "ApprovalProvider",
    "CallbackApprovalProvider",
    "StaticApprovalProvider",
    "ANTHROPIC_COMPAT_BASE_URL_ENV",
    "ANTHROPIC_COMPAT_DEFAULT_MODEL",
    "ANTHROPIC_COMPAT_ENV_KEY",
    "ANTHROPIC_COMPAT_MODEL_ENV",
    "anthropic_compatible_messages_transport",
    "CalibrationResult",
    "ChangeProposal",
    "ChangeTestResult",
    "CompilerAuditPolicy",
    "evaluate_change_test",
    "DomainContext",
    "ConnectorSpec",
    "DomainPluginPack",
    "DomainPluginRegistry",
    "DomainRulePack",
    "deliberate_next_action",
    "deliberate_chain",
    "DeliberationEvent",
    "dumps_event_payloads",
    "EventLog",
    "Event",
    "FailureMode",
    "FailureRecord",
    "HandoffStageResult",
    "events_to_payloads",
    "HandoffValidationResult",
    "LLMTaskCompiler",
    "LLMProvider",
    "LLMProviderError",
    "LLMProviderRequest",
    "LLMProviderResponse",
    "ProviderBackedTaskCompiler",
    "ProviderTransport",
    "FailingLLMProvider",
    "EnvironmentLLMProvider",
    "EvaluatorPlugin",
    "ALL_COGNITIVE_PRIMITIVES",
    "CognitivePrimitive",
    "OPENAI_DEFAULT_MODEL",
    "OPENAI_ENV_KEY",
    "OPENAI_MODEL_ENV",
    "NextAction",
    "ObservationCandidate",
    "ObservationEvent",
    "GlossaryPack",
    "StaticLLMTaskCompiler",
    "StaticLLMProvider",
    "EmbeddingProvider",
    "StaticEmbeddingProvider",
    "get_default_embedding_provider",
    "TASK_SPEC_JSON_SCHEMA",
    "build_disabled_provider_transport",
    "build_anthropic_compatible_request_body",
    "build_belief_payload",
    "build_domain_context",
    "build_handoff_report",
    "assess_handoff_stage_gates",
    "build_anthropic_compatible_task_compiler_provider",
    "build_openai_task_compiler_provider",
    "build_observation_event",
    "build_quality_report",
    "CommitmentKind",
    "DeltaPolicyDecision",
    "PlanExecutionResult",
    "PlanSpec",
    "PlannerToolExecutionResult",
    "QualityGateCheck",
    "QualityGateResult",
    "QualityMetrics",
    "ReasoningStep",
    "ReasoningChain",
    "RunResult",
    "RunArtifact",
    "DELIBERATION_EVENT_SCHEMA_VERSION",
    "COMMITMENT_POLICY_SCHEMA_VERSION",
    "PLAN_SCHEMA_VERSION",
    "REASONING_STEP_SCHEMA_VERSION",
    "RUN_ARTIFACT_SCHEMA_VERSION",
    "SCHEMA_MAJOR_VERSION",
    "TASK_SCHEMA_VERSION",
    "TaskLevel",
    "TaskSpec",
    "InMemoryReadOnlyToolRunner",
    "ToolGateway",
    "ToolGatewayResult",
    "ApprovalProvider",
    "GatewayStaticApprovalProvider",
    "build_tool_gateway",
    "ReadToolHandler",
    "ToolCallSpec",
    "ToolCallEvent",
    "ToolPolicyDecision",
    "ToolRegistry",
    "ToolResultEvent",
    "ToolObservationFlowResult",
    "ToolSpec",
    "build_task_compiler_prompt",
    "build_tool_call_event",
    "compile_task",
    "classify_exception",
    "classify_task_level",
    "compile_task_with_llm_adapter",
    "describe_failure_mode",
    "default_primitives_for_task_kind",
    "evaluate_delta_policy",
    "evaluate_delta_policy_in_domain",
    "evaluate_tool_call_policy",
    "execute_task",
    "execute_task_in_domain",
    "execute_task_with_chain",
    "execute_task_with_compiler",
    "execute_task_with_compiler_in_domain",
    "execute_plan",
    "execute_plan_with_read_only_tools",
    "extract_anthropic_compatible_text",
    "loads_event_payloads",
    "load_handoff_state",
    "assess_quality_gates",
    "assess_quality_gates_for_run",
    "compute_quality_metrics",
    "render_event_narration",
    "render_handoff_report",
    "render_quality_report",
    "plan_from_task",
    "parse_llm_task_response",
    "openai_responses_task_compiler_transport",
    "openai_responses_task_compiler_transport_with_client",
    "observation_from_tool_result",
    "promote_belief_candidate_to_delta",
    "promote_observation_to_delta",
    "promote_observation_to_belief_delta",
    "reflect_and_redirect",
    "RedirectProposal",
    "record_failure",
    "require_schema_version",
    "run_result_to_artifact",
    "run_allowed_tool_call_observation_flow",
    "run_read_only_tool_observation_flow",
    "validate_handoff_state",
    "validate_handoff_state_file",
    "validate_primitives",
    # Plan B new modules
    "PrecedentMemory",
    "MemoryRetrievalResult",
    "EvidenceNode",
    "EvidenceEdge",
    "EvidenceGraph",
    "EvidenceNodeType",
    "EvidenceEdgeType",
    "RetrievalQuery",
    "MemoryStore",
    "MemoryIndex",
    "Contextualizer",
    "DocumentChunk",
    "Retriever",
    "RetrievalResult",
    "EvidenceGraphBuilder",
    "EvidenceGraphAnalyzer",
    "ContextRestorer",
    "RestoredContext",
    "ExecutionStage",
    "UncertaintyRouter",
    "RoutingSignals",
    "RoutingResult",
    "RoutingDecision",
    "RouterConfig",
    "ApprovalPacket",
    "ApprovalVerdict",
    "ABTestingFramework",
    "ABExperiment",
    "ExperimentVariant",
    "ExperimentResult",
    "ExperimentAnalysis",
    "ExperimentStatus",
    "LLMDeliberationCompiler",
    "ProviderBackedDeliberationCompiler",
    "StaticLLMDeliberationCompiler",
    "deliberate_chain_with_llm",
    "deliberate_with_llm",
    "parse_llm_deliberation_response",
    "LLMPlanCompiler",
    "ProviderBackedPlanCompiler",
    "StaticLLMPlanCompiler",
    "plan_with_llm",
    "parse_llm_plan_response",
    "EnvironmentEmbeddingProvider",
    "OpenAIEmbeddingProvider",
    "build_openai_embedding_provider",
    "DefaultToolSandbox",
    "SandboxedToolExecutor",
    "ToolExecutionContext",
    "ToolExecutionResult",
    "ToolHandler",
    "ToolSandbox",
    "StateStore",
    "PersistenceSnapshot",
    "EventStoreEntry",
    "load_world_state_from_file",
    "save_world_state",
    "load_world_state",
    "ExecutionMetricsCollector",
    "ExecutionObserver",
    "ExecutionPhase",
    "ConsoleMetricsExporter",
    "DebugContext",
    "ExecutionMetric",
    "MetricsExporter",
    "PhaseTiming",
    "HTTPGateway",
    "HTTPGatewayConfig",
    "WebhookConfig",
    "WebhookDispatcher",
    "DefaultWebhookSender",
    "RateLimiter",
    "ImportExportManager",
    "ExportPackage",
    "ExportManifest",
    "Confidence",
    "RevisionDelta",
    "RevisionTargetKind",
    "WorldEntity",
    "WorldHypothesis",
    "WorldRelation",
    "WORLD_SCHEMA_VERSION",
    "WorldState",
    "add_anchor_facts",
    "add_entity",
    "add_hypothesis_to_world",
    "add_relation",
    "add_tension",
    "remove_entity",
    "resolve_tension",
    "update_entity",
    "update_hypothesis_status",
    "update_self_model",
    "WORLD_STATE_SCHEMA_VERSION",
    "CommitmentEvent",
    "FullCommitmentKind",
    "Reversibility",
    "complete_commitment",
    "make_act_commitment",
    "make_observation_commitment",
    "make_tool_contact_commitment",
    "COMMITMENT_SCHEMA_VERSION",
    "CommitmentPolicy",
    "CommitmentPolicyDecision",
    "DefaultCommitmentPolicy",
    "evaluate_commitment_policy",
    "ModelRevisionEvent",
    "RevisionKind",
    "revise_from_commitment",
    "REVISION_SCHEMA_VERSION",
    "DefaultRevisionPolicy",
    "RevisionPolicy",
    "RevisionPolicyDecision",
    "evaluate_revision_policy",
    "REVISION_POLICY_SCHEMA_VERSION",
    "HypothesisCandidate",
    "generate_from_tension",
    "generate_from_conflict",
    "rank_hypotheses",
]
